name: CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Embed PlantUML inside Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build PlantUML
        uses: alessandro-marcantoni/puml-markdown@v0.1.1